### ISSUE TITLE
Fix SQRT fn for secp256r1 after accidental merge

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/halo2curves#52]
While editing the PR, I accidentally merged the PR. 
The only test that is not passing after my fixes in https://github.com/privacy-scaling-explorations/halo2curves/commit/1fc3b8357c237ed025293b98f0626cb26169c554 and 2ce9e2318a9bc8f6f25acf6051d02406793d3348 is the `sqrt()` fn for `secp256r1::Fq`.

@rrrliu could you try to fix it? I've been trying the whole day and haven't succeeded. Otherwise, I'll pair up with @davidnevadoc and try to fix it.

Apologies for the inconvencience

**Comment by rrrliu** [comment]
All good - I'm out today but have a lot of time tomorrow to fix!

**Comment by huitseeker** [comment]
This should be fixed in #54, but for the purpose of avoiding this sort of issue occurring again, perhaps this repo could use a GH merge queue?
https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

The CI changes are ~3 lines which I can totally tack on :
https://github.com/privacy-scaling-explorations/halo2curves/pull/56
(there are settings changes in the branch protection rules, which an admin of the repo would have to do ofc)

**Comment by huitseeker** [comment]
@CPerezz since we have both a merge queue and #54, we may want to close this.
